name: Deploy to HostAfrica
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build

      - name: Verify FTP Connection
        run: |
          nc -zv ftp.sminfinitetech.co.za 21
          curl -v ftp://ftp.sminfinitetech.co.za

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.sminfinitetech.co.za
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: /public_html/
          protocol: ftp
          dangerous-clean-slate: true
